paths:
  /api/products/:
    get:
      tags:
        - Productos  
      summary: Obtener todos los productos
      parameters:
        - in: query
          name: page
          schema:
            type: Number
          description: Numero de pagina .
        - in: query
          name: limit
          schema:
            type: Number
          description: Cantidad de productos.
        - in: query
          name: sort
          schema:
            type: String
          description: \'asc\' para acendente, \'desc\' para decendente.
      responses:
        '200':
          description: Respuesta exitosa.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/Product'
          '500':
            description: Error interno del servidor, usualmente generado por una query defectuosa o un fallo d econexion en la base de datos.
    post:
      tags:
        - Productos  
      summary: Crear un nuevo producto
  /api/products/{productId}:
    get:
        tags:
          - Productos  
        summary: Obtener un productos
    put:
      tags:
        - Productos  
      summary: Actualizar un producto
    delete:
      tags:
        - Productos  
      summary: Eliminar un product
  


components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: ObjectId
          description: Id autogenerado de mongo
        code:
          type: string
          description: Código del producto.
          unique: true
        title:
          type: string
          description: Título del producto.
        description:
          type: string
          description: Descripción del producto.
        price:
          type: number
          description: Precio del producto.
        status:
          type: boolean
          description: Estado del producto.
          default: true
        stock:
          type: number
          description: Stock disponible del producto.
        category:
          type: string
          description: Categoría del producto.
        thumbnails:
          type: array
          description: Lista de URLs de las miniaturas del producto.
          items:
            type: string
      example:
        id: 64c06ee6e751fdc36d8aa519
        code: "Codigo-new-2"
        title: "producto 2"
        description: "Descripcion del producto nuevo"
        price: 200
        status: false
        stock: 40
        category: Talleres
        thumbnails: ["url.jpg"]

